### ISSUE TITLE
fiberloss problems

### ISSUE THREAD

**Issue by sbailey** [desihub/specsim#72]
I'm trying to generate a fiberloss table for different galaxy parameters following the instructions at http://specsim.readthedocs.io/en/stable/fiberloss.html

`quickspecsim -c desi-elg --save-fiberloss desi-elg-fiberloss` generates a fits file with 70 HDUs but apparently not the ecsv file needed to pass back into the config file.

`quickfiberloss` has a number of the shape parameters that I would like to vary (handy instead of having to edit the yaml file for each variation), but it apparently doesn't have a way to save the results, and that script is currently broken:
```
[cori08 ~] quickfiberloss -n 100 --disk-fraction 0.5 --bulge-fraction 0.5
Traceback (most recent call last):
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/specsim/v0.9/bin/quickfiberloss", line 11, in <module>
    load_entry_point('specsim==0.9', 'console_scripts', 'quickfiberloss')()
  File "/global/common/cori/contrib/desi/desiconda/20170613-1.1.4-spectro/code/specsim/v0.9/lib/python3.5/site-packages/specsim-0.9-py3.5.egg/specsim/quickfiberloss.py", line 66, in main
    simulator.atmosphere.seeing['fwhm_ref'] = args.seeing * u.arcsec
AttributeError: 'Atmosphere' object has no attribute 'seeing'
```

I can probably derive what I need from the underlying code, but it would be helpful to have these outer wrapper scripts working again too.

**Comment by tolgayapici** [comment]
I committed a fix to the dithering branch. I will request a pull.

**Comment by dkirkby** [comment]
The command mentioned above is working in the latest tag (v0.12):
```
quickfiberloss -n 100 --disk-fraction 0.5 --bulge-fraction 0.5
```
Closing now, but re-open if I misunderstood the issue.
